### ISSUE TITLE
How exactly do I use the output for honeyhunters set builder?

### ISSUE THREAD

**Issue by lombax5832** [clicksilver/mhw_decos_csv#1]
I get an output like:

`{"Defense Jewel+ 4":3,"Hard Defense Jewel 4":0,"Recovery Jewel+ 4":4,"Fire Res Jewel+ 4":4,"Hard Fire Res Jewel 4":0,"Water Res Jewel+ 4":6,"Hard Water Res Jewel 4":0,"Ice Res Jewel+ 4":1,"Hard Ice Res Jewel 4":0,"Thunder Res Jewel+ 4":4,"Hard Thunder Res Jewel 4":0,"Dragon Res Jewel+ 4":3,"Hard Dragon Res Jewel 4":0,"Antidote Jewel+ 4":1,"Antipara Jewel+ 4":1,"Pep Jewel+ 4":4,"Antiblast Jewel+ 4":1,"Steadfast Jewel+ 4":1,"Suture Jewel+ 4":2,"Def Lock Jewel+ 4":6,"Miasma Jewel+ 4":3,"Wind Resist Jewel+ 4":0,"Expert Jewel+ 4":1,"Blaze Jewel+ 4":2,"Stream Jewel+ 4":3,"Frost Jewel+ 4":4,"Bolt Jewel+ 4":1,"Dragon Jewel+ 4":2,"Venom Jewel+ 4":0,"Paralyzer Jewel+ 4":2,"Sleep Jewel+ 4":1,"Blast Jewel+ 4":2,"Artillery Jewel+ 4":4,"Sonorous Jewel+ 4":3,"Potential Jewel+ 4":0,"Physique Jewel+ 4":2,"Hungerless Jewel+ 4":4,"Enduring Jewel+ 4":2,"Hard Enduring Jewel 4":0,"Friendship Jewel+ 4":5,"Specimen Jewel+ 4":2,"Hard Specimen Jewel 4":0,"Botany Jewel+ 4":2,"Hard Botany Jewel 4":0,"Geology Jewel+ 4":1,"Hard Geology Jewel 4":0,"Survival Jewel+ 4":4,"Hard Survival Jewel 4":0,"Mirewalker Jewel+ 4":1,"Intimidator Jewel+ 4":2,"Hard Intimidator Jewel 4":3,"Tip Toe Jewel+ 4":2,"Hard Tip Toe Jewel 4":1,"Meowster Jewel+ 4":2,"Hard Meowster Jewel 4":1,"Evasion Jewel+ 4":0,"Earplug Jewel+ 4":0,"Ironwall Jewel+ 4":2,"Heavy Artillery Jewel+ 4":2,"Furor Jewel+ 4":1,"Attack Jewel+ 4":0,"Challenger Jewel+ 4":0,"Trueshot Jewel+ 4":0,"Throttle Jewel+ 4":1,"Handicraft Jewel+ 4":0,"Brace/Protection Jewel 4":1,"Wind Resist/Protection Jewel 4":2,"Footing/Protection Jewel 4":1,"Draw/Protection Jewel 4":1,"Enhancer/Protection Jewel 4":1,"Charger/Protection Jewel 4":0,"Destroyer/Protection Jewel 4":1,"KO/Protection Jewel 4":1,"Throttle/Protection Jewel 4":1,"Challenger/Protection Jewel 4":1,"Flawless/Protection Jewel 4":1,"Potential/Protection Jewel 4":3,"Mighty/Protection Jewel 4":1,"Furor/Protection Jewel 4":1,"Phoenix/Protection Jewel 4":1,"Earplug/Protection Jewel 4":0,"Critical/Protection Jewel 4":2,"Tenderizer/Protection Jewel 4":0,"Handicraft/Protection Jewel 4":0,"Release/Protection Jewel 4":1,"Brace/Vitality Jewel 4":0,"Wind Resist/Vitality Jewel 4":1,"Footing/Vitality Jewel 4":0,"Draw/Vitality Jewel 4":0,"Enhancer/Vitality Jewel 4":1,"Charger/Vitality Jewel 4":0,"Destroyer/Vitality Jewel 4":1,"KO/Vitality Jewel 4":1,"Throttle/Vitality Jewel 4":1,"Challenger/Vitality Jewel 4":1,"Flawless/Vitality Jewel 4":0,"Potential/Vitality Jewel 4":0,"Mighty/Vitality Jewel 4":1,"Furor/Vitality Jewel 4":0,"Phoenix/Vitality Jewel 4":0,"Earplug/Vitality Jewel 4":0,"Critical/Vitality Jewel 4":2,"Tenderizer/Vitality Jewel 4":0,"Handicraft/Vitality Jewel 4":0,"Release/Vitality Jewel 4":0,"Brace/Medicine Jewel 4":0,"Wind Resist/Medicine Jewel 4":1,"Footing/Medicine Jewel 4":3,"Draw/Medicine Jewel 4":2,"Enhancer/Medicine Jewel 4":1,"Charger/Medicine Jewel 4":1,"Destroyer/Medicine Jewel 4":3,"KO/Medicine Jewel 4":1,"Throttle/Medicine Jewel 4":1,"Challenger/Medicine Jewel 4":1,"Flawless/Medicine Jewel 4":0,"Potential/Medicine Jewel 4":0,"Mighty/Medicine Jewel 4":2,"Furor/Medicine Jewel 4":2,"Phoenix/Medicine Jewel 4":0,"Earplug/Medicine Jewel 4":0,"Critical/Medicine Jewel 4":0,"Tenderizer/Medicine Jewel 4":0,"Handicraft/Medicine Jewel 4":0,"Release/Medicine Jewel 4":0,"Resistor/Attack Jewel 4":2,"Drain/Attack Jewel 4":1,"Flight/Attack Jewel 4":0,"Sheath/Attack Jewel 4":2,"Fortitude/Attack Jewel 4":2,"Slider/Attack Jewel 4":4,"Sprinter/Attack Jewel 4":1,"Refresh/Attack Jewel 4":2,"Crisis/Attack Jewel 4":2,"Jumping/Attack Jewel 4":0,"Ironwall/Attack Jewel 4":2,"Guardian/Attack Jewel 4":5,"Friendship/Attack Jewel 4":1,"Gobbler/Attack Jewel 4":1,"Satiated/Attack Jewel 4":3,"Grinder/Attack Jewel 4":1,"Bomber/Attack Jewel 4":1,"Fungiform/Attack Jewel 4":3,"Stonethrower/Attack Jewel 4":3,"Resistor/Expert Jewel 4":0,"Drain/Expert Jewel 4":0,"Flight/Expert Jewel 4":1,"Sheath/Expert Jewel 4":1,"Fortitude/Expert Jewel 4":3,"Slider/Expert Jewel 4":3,"Sprinter/Expert Jewel 4":1,"Refresh/Expert Jewel 4":1,"Crisis/Expert Jewel 4":1,"Jumping/Expert Jewel 4":2,"Ironwall/Expert Jewel 4":3,"Guardian/Expert Jewel 4":6,"Friendship/Expert Jewel 4":0,"Gobbler/Expert Jewel 4":0,"Satiated/Expert Jewel 4":3,"Grinder/Expert Jewel 4":1,"Bomber/Expert Jewel 4":2,"Fungiform/Expert Jewel 4":0,"Stonethrower/Expert Jewel 4":3,"Resistor/Handicraft Jewel 4":0,"Drain/Handicraft Jewel 4":0,"Flight/Handicraft Jewel 4":0,"Sheath/Handicraft Jewel 4":1,"Fortitude/Handicraft Jewel 4":2,"Slider/Handicraft Jewel 4":2,"Sprinter/Handicraft Jewel 4":0,"Refresh/Handicraft Jewel 4":0,"Crisis/Handicraft Jewel 4":1,"Jumping/Handicraft Jewel 4":0,"Ironwall/Handicraft Jewel 4":0,"Guardian/Handicraft Jewel 4":1,"Friendship/Handicraft Jewel 4":0,"Gobbler/Handicraft Jewel 4":0,"Satiated/Handicraft Jewel 4":1,"Grinder/Handicraft Jewel 4":0,"Bomber/Handicraft Jewel 4":0,"Fungiform/Handicraft Jewel 4":0,"Stonethrower/Handicraft Jewel 4":0,"Resistor/Release Jewel 4":0,"Drain/Release Jewel 4":2,"Flight/Release Jewel 4":0,"Sheath/Release Jewel 4":1,"Fortitude/Release Jewel 4":0,"Slider/Release Jewel 4":2,"Sprinter/Release Jewel 4":0,"Refresh/Release Jewel 4":0,"Crisis/Release Jewel 4":0,"Jumping/Release Jewel 4":0,"Ironwall/Release Jewel 4":0,"Guardian/Release Jewel 4":0,"Friendship/Release Jewel 4":0,"Gobbler/Release Jewel 4":0,"Satiated/Release Jewel 4":0,"Grinder/Release Jewel 4":0,"Bomber/Release Jewel 4":0,"Fungiform/Release Jewel 4":0,"Stonethrower/Release Jewel 4":1,"Brace/Physique Jewel 4":0,"Wind Resist/Physique Jewel 4":0,"Footing/Physique Jewel 4":0,"Draw/Physique Jewel 4":0,"Enhancer/Physique Jewel 4":2,"Charger/Physique Jewel 4":0,"Destroyer/Physique Jewel 4":0,"KO/Physique Jewel 4":0,"Throttle/Physique Jewel 4":0,"Challenger/Physique Jewel 4":0,"Flawless/Physique Jewel 4":2,"Potential/Physique Jewel 4":0,"Mighty/Physique Jewel 4":0,"Furor/Physique Jewel 4":0,"Phoenix/Physique Jewel 4":0,"Earplug/Physique Jewel 4":0,"Critical/Physique Jewel 4":0,"Tenderizer/Physique Jewel 4":0,"Handicraft/Physique Jewel 4":0,"Release/Physique Jewel 4":0,"Resistor/Physique Jewel 4":0,"Drain/Physique Jewel 4":0,"Flight/Physique Jewel 4":0,"Sheath/Physique Jewel 4":0,"Fortitude/Physique Jewel 4":3,"Slider/Physique Jewel 4":7,"Sprinter/Physique Jewel 4":0,"Refresh/Physique Jewel 4":1,"Crisis/Physique Jewel 4":2,"Jumping/Physique Jewel 4":1,"Ironwall/Physique Jewel 4":0,"Guardian/Physique Jewel 4":3,"Friendship/Physique Jewel 4":0,"Gobbler/Physique Jewel 4":0,"Satiated/Physique Jewel 4":3,"Grinder/Physique Jewel 4":1,"Bomber/Physique Jewel 4":2,"Fungiform/Physique Jewel 4":3,"Stonethrower/Physique Jewel 4":7,"Brace/Evasion Jewel 4":0,"Wind Resist/Evasion Jewel 4":0,"Footing/Evasion Jewel 4":0,"Draw/Evasion Jewel 4":0,"Enhancer/Evasion Jewel 4":0,"Charger/Evasion Jewel 4":0,"Destroyer/Evasion Jewel 4":0,"KO/Evasion Jewel 4":0,"Throttle/Evasion Jewel 4":1,"Challenger/Evasion Jewel 4":1,"Flawless/Evasion Jewel 4":0,"Potential/Evasion Jewel 4":1,"Mighty/Evasion Jewel 4":0,"Furor/Evasion Jewel 4":0,"Phoenix/Evasion Jewel 4":0,"Earplug/Evasion Jewel 4":0,"Critical/Evasion Jewel 4":0,"Tenderizer/Evasion Jewel 4":0,"Handicraft/Evasion Jewel 4":0,"Release/Evasion Jewel 4":0,"Resistor/Evasion Jewel 4":1,"Drain/Evasion Jewel 4":0,"Flight/Evasion Jewel 4":2,"Sheath/Evasion Jewel 4":0,"Fortitude/Evasion Jewel 4":2,"Slider/Evasion Jewel 4":2,"Sprinter/Evasion Jewel 4":0,"Refresh/Evasion Jewel 4":0,"Crisis/Evasion Jewel 4":1,"Jumping/Evasion Jewel 4":2,"Ironwall/Evasion Jewel 4":3,"Guardian/Evasion Jewel 4":4,"Friendship/Evasion Jewel 4":1,"Gobbler/Evasion Jewel 4":0,"Satiated/Evasion Jewel 4":3,"Grinder/Evasion Jewel 4":1,"Bomber/Evasion Jewel 4":1,"Fungiform/Evasion Jewel 4":0,"Stonethrower/Evasion Jewel 4":5,"Brace/Maintenance Jewel 4":1,"Wind Resist/Maintenance Jewel 4":0,"Footing/Maintenance Jewel 4":2,"Draw/Maintenance Jewel 4":1,"Enhancer/Maintenance Jewel 4":1,"Charger/Maintenance Jewel 4":1,"Destroyer/Maintenance Jewel 4":0,"KO/Maintenance Jewel 4":1,"Throttle/Maintenance Jewel 4":2,"Challenger/Maintenance Jewel 4":1,"Flawless/Maintenance Jewel 4":3,"Potential/Maintenance Jewel 4":2,"Mighty/Maintenance Jewel 4":2,"Furor/Maintenance Jewel 4":1,"Phoenix/Maintenance Jewel 4":0,"Earplug/Maintenance Jewel 4":0,"Critical/Maintenance Jewel 4":0,"Tenderizer/Maintenance Jewel 4":0,"Handicraft/Maintenance Jewel 4":0,"Release/Maintenance Jewel 4":0,}`

But, I'm not sure how I can use this for honeyhunters set builder site.

**Comment by lombax5832** [comment]
I was able to change the function call in main() before building, but maybe there should be a command line argument to make this easier?

Otherwise this is a great tool, thanks for making it

**Comment by clicksilver** [comment]
@lombax5832 Hi there! Sorry I didn't respond in time. I actually forgot about this project but there's a full release now here: https://github.com/clicksilver/mhw_decos_csv/releases

Good job figuring it out! Sorry for the lazy organization. The format you got was for the armor set builder for MHW Wiki-DB (https://mhw.wiki-db.com/sim/?hl=en).
